### PR TITLE
Use go modules for dependency management

### PR DESCRIPTION
**Pull request by miguelmota**
This package is lacking dependency management, so any upstream package that makes breaking changes will break this package. Vendor packages should be locked into tagged versions or revisions to prevent breaking this package

## Description
Fixes issue https://github.com/immutability-io/vault-ethereum/issues/51 by using [go modules](https://github.com/golang/go/wiki/Modules)

## Types of changes

- [ ] Documentation enhancement
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by cypherhat** [comment]
Do we need to checkin Vendor files? I didn't think we needed to do that.

**Comment by richard-mauri** [comment]
No, you don't need vendor files.

I spent a few hours characterizing the build fault and contributing a fix that works, so in exchange for that and future contributions!, please merge of #55

**Comment by cypherhat** [comment]
I merged Richard's PR. I am gonna close this one. Thanks Miguel!

**Comment by miguelmota** [comment]
@cypherhat Go doesn't provide a centralized index of repositories like NPM or Cargo, so if one of your dependencies moves or disappears you're out of luck

Go best practices are agnostic to vendor check-in https://github.com/golang/dep/blob/master/docs/FAQ.md#should-i-commit-my-vendor-directory

**Comment by miguelmota** [comment]
@cypherhat @richard-mauri 

Go doesn't provide a centralized index of repositories like NPM or Cargo, so if one of your dependencies moves or disappears you're out of luck

Go best practices are agnostic to vendor check-in: https://github.com/golang/dep/blob/master/docs/FAQ.md#should-i-commit-my-vendor-directory

you an see go-ethereum checks in their vendor directory: https://github.com/ethereum/go-ethereum/tree/master/vendor

**Pull request closed without merging**
